<?php
/**
 * @file
 * CiviCRM Flush Caches
 */
 
/**
 * Implementation of hook_flush_caches().
 */
function civicrm_clear_all_caches_flush_caches() {
  
  if (!civicrm_initialize()) {
    watchdog('civicrm_clear_all_caches', t('Failed to initialize CiviCRM'));
    return;
  }

  require_once('api/v3/System.php');

  // Flush all caches using the API
  // Skip triggers and sessions to minimize impact.
  $params = array(
    'version' => 3,
    'triggers' => 0,
    'session' => 0
  );
  $result = civicrm_api('System', 'flush', $params);

  if ($result['is_error']) {
    watchdog('civicrm_clear_all_caches', t('An error occurred: !message', array('!message' => $result['error_message'])), WATCHDOG_ERROR);
    return;
  }
  watchdog('civicrm_clear_all_caches', t('CiviCRM caches, templates and menus have been rebuilt. Triggers and sessions were not flushed. Use "drush cc all" to do a full flush.'));
}

